language: node_js

node_js:
  - "9"

install:
  - yarn install

before_script:
  - mkdir -p ~/.ssh
  - echo ${SSH_PRIVATE_KEY} | base64 -d > ~/.ssh/id_rsa
  - chmod go-rwx ~/.ssh/id_rsa

script:
  - yarn lint
  - yarn build

deploy:
  provider: script
  script:  scp -r -o StrictHostKeyChecking=no -P 22022 $TRAVIS_BUILD_DIR/dist/* www-data@labs.safefleet.eu:/var/www/labs-web-app
  on:
    branch: master
